// Comments API — uses Supabase REST (no SDK needed, just env vars)
//
// Setup (free): https://supabase.com → New project → SQL Editor → run:
//
//   create table comments (
//     id bigint generated by default as identity primary key,
//     post_slug text not null,
//     name text not null,
//     email text,
//     message text not null,
//     created_at timestamptz default now()
//   );
//   alter table comments enable row level security;
//   create policy "Public read" on comments for select using (true);
//   create policy "Public insert" on comments for insert with check (true);
//
// Then add to Vercel environment variables:
//   NEXT_PUBLIC_SUPABASE_URL   = https://xxxx.supabase.co
//   NEXT_PUBLIC_SUPABASE_ANON_KEY = eyJ...

const SB_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SB_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

function sbHeaders() {
  return {
    apikey: SB_KEY,
    Authorization: `Bearer ${SB_KEY}`,
    'Content-Type': 'application/json',
  }
}

// GET /api/comments?slug=some-post-slug
export async function GET(request) {
  const { searchParams } = new URL(request.url)
  const slug = searchParams.get('slug')

  if (!slug) {
    return Response.json({ comments: [], error: 'Missing slug' }, { status: 400 })
  }

  if (!SB_URL || !SB_KEY) {
    return Response.json({ comments: [], notice: 'Database not configured yet' })
  }

  try {
    const res = await fetch(
      `${SB_URL}/rest/v1/comments?post_slug=eq.${encodeURIComponent(slug)}&order=created_at.asc&select=name,message,created_at`,
      { headers: sbHeaders(), cache: 'no-store' }
    )
    if (!res.ok) throw new Error(await res.text())
    const comments = await res.json()
    return Response.json({ comments: comments || [] })
  } catch (err) {
    return Response.json({ comments: [], error: 'Failed to fetch comments' }, { status: 500 })
  }
}

// POST /api/comments
// body: { postSlug, name, email, message }
export async function POST(request) {
  let body
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const { postSlug, name, email, message } = body

  // Basic server-side validation
  if (!postSlug || typeof postSlug !== 'string') {
    return Response.json({ error: 'Missing post slug' }, { status: 400 })
  }
  if (!name || name.trim().length < 2 || name.trim().length > 80) {
    return Response.json({ error: 'Invalid name' }, { status: 400 })
  }
  if (!message || message.trim().length < 10 || message.trim().length > 1200) {
    return Response.json({ error: 'Invalid message' }, { status: 400 })
  }
  if (email && (typeof email !== 'string' || email.length > 120)) {
    return Response.json({ error: 'Invalid email' }, { status: 400 })
  }

  // Honeypot: reject if any extra unknown field is present (catches naive bots)
  const allowedKeys = new Set(['postSlug', 'name', 'email', 'message'])
  if (Object.keys(body).some(k => !allowedKeys.has(k))) {
    return Response.json({ error: 'Bad request' }, { status: 400 })
  }

  if (!SB_URL || !SB_KEY) {
    // DB not set up yet — acknowledge gracefully
    return Response.json({ success: true, notice: 'Database not configured yet — comment noted' })
  }

  try {
    const res = await fetch(`${SB_URL}/rest/v1/comments`, {
      method: 'POST',
      headers: { ...sbHeaders(), Prefer: 'return=minimal' },
      body: JSON.stringify({
        post_slug: postSlug.trim().slice(0, 200),
        name: name.trim().slice(0, 80),
        email: email ? email.trim().slice(0, 120) : null,
        message: message.trim().slice(0, 1200),
      }),
    })

    if (!res.ok) throw new Error(await res.text())
    return Response.json({ success: true })
  } catch (err) {
    return Response.json({ error: 'Failed to save comment' }, { status: 500 })
  }
}
